spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: postgres
  jpa:
    generate-ddl: false
    show-sql: true

security:
  jwt:
    secretKey: 123123213123123123123123123123213123213213123213123321312312312321321321323
    access-token-validity-in-seconds: 60000

cache:
  expirationTimeInMinutes: 1